apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: custom-scheduler
  labels:
    app: custom-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: custom-scheduler
      resourceNamespace: custom-scheduler
    profiles:
    - schedulerName: custom-scheduler
      plugins:
        preFilter:
          enabled:
          - name: []
        filter:
          enabled:
          - name: ImageCompatibilityFilter
      pluginConfig:
      - name: ImageCompatibilityFilter
        args: {}
