apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: custom-scheduler
  labels:
    app: custom-scheduler
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: custom-scheduler
      resourceNamespace: custom-scheduler
    profiles:
    - schedulerName: custom-scheduler
      plugins:
        queueSort:
          enabled:
          - name: PrioritySort
          disabled:
          - name: "*"
        preFilter:
          enabled:
          - name: NodeResourcesFit
          - name: NodeAffinity
          disabled:
          - name: "*"
        filter:
          enabled:
          - name: NodeUnschedulable
          - name: NodeResourcesFit
          - name: NodeAffinity
          - name: TaintToleration
          - name: ImageCompatibilityFilter
          disabled:
          - name: "*"
        preScore:
          enabled: []
          disabled:
          - name: "*"
        score:
          enabled:
          - name: NodeResourcesBalancedAllocation
            weight: 1
          - name: NodeAffinity
            weight: 1
          - name: TaintToleration
            weight: 1
          disabled:
          - name: "*"
        reserve:
          enabled: []
          disabled:
          - name: "*"
        preBind:
          enabled: []
          disabled:
          - name: "*"
        bind:
          enabled:
          - name: DefaultBinder
          disabled:
          - name: "*"
        postBind:
          enabled: []
          disabled:
          - name: "*"
        permit:
          enabled: []
          disabled:
          - name: "*"
      pluginConfig:
      - name: ImageCompatibilityFilter
        args: {}
