apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: custom-scheduler

resources:
- namespace.yaml
- serviceaccount.yaml
- rbac.yaml
- configmap.yaml
- deployment.yaml

commonLabels:
  app: custom-scheduler
